ssh_authorized_keys:
  - github:nomaster
  - github:mraerino

k3os:
  data_sources:
    - cdrom
  sysctl:
    net.ipv6.conf.eth0.accept_ra: "2"

write_files:
  # enable qemu-guest-agent
  # ref: https://github.com/rancher/k3os/issues/291
  - path: /etc/setup-qemu-guest-agent.sh
    content: |-
      #!/bin/bash

      for i in 0 1 2 3; do
        if [ -c /dev/vport${i}p1 ]; then
          echo "GA_PATH=\"/dev/vport${i}p1\"" > /etc/conf.d/qemu-guest-agent
          /etc/init.d/qemu-guest-agent restart
          exit 0
        fi
      done
    owner: root
    permissions: "0755"

boot_cmd:
  - /etc/setup-qemu-guest-agent.sh
